name: Release
on:
  push:
    branches: ["*"]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - uses: olafurpg/setup-scala@v10
      - run: sbt clean test
      - if: always()
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'target/test-reports/**/*.xml'
      - if: contains(steps.file_changes.outputs.files, 'version.sbt')
        uses: blended-zio/setup-gpg@v3
      - if: contains(steps.file_changes.outputs.files, 'version.sbt')
        run: sbt ci-publish
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
