name: Release
on:
  push:
    branches: ["*"]
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
    outputs:
      should_publish: ${{ contains(steps.file_changes.outputs.files, 'version.sbt') }}
  build:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
      - run: sbt clean test
#       - name: Publish Unit Test Results
#         uses: EnricoMi/publish-unit-test-result-action@v1
#         if: always()
#         with:
#           files: target/test-reports/**/*.xml      
      - if: needs.should_publish
        uses: blended-zio/setup-gpg@v3
      - if: needs.should_publish
        run: sbt ci-publish
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
